In [1]:
import numpy as np

## DataTypes & Attributes

In [2]:
# NumPy's main datatype is ndarray
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1, 2.0, 3.3], [4, 5, 6.5]])

a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [5]:
a3 = np.array([[[1, 2, 3],
               [4, 5, 6],
              [7, 8, 9]],
             [[10, 11, 12],
             [13, 14, 15],
             [16, 17, 18]]])

In [6]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [7]:
a1.shape

(3,)

In [8]:
a2.shape

(2, 3)

In [9]:
a3.shape

(2, 3, 3)

In [10]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [11]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [12]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [13]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [14]:
# Create a DataFrame from a NumPy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## 2. Creating arrays

In [15]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [16]:
sample_array.dtype

dtype('int32')

In [17]:
ones = np.ones((2, 3))

In [18]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [19]:
ones.dtype

dtype('float64')

In [20]:
type(ones)

numpy.ndarray

In [21]:
zeros = np.zeros((2, 3))

In [22]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [24]:
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[4, 7, 5, 8, 2],
       [6, 8, 4, 7, 8],
       [1, 6, 1, 1, 3]])

In [25]:
random_array.size

15

In [26]:
random_array.shape

(3, 5)

In [27]:
random_array_2 = np.random.random((5, 3))

random_array_2

array([[0.81972642, 0.60325128, 0.56184462],
       [0.01335601, 0.56291752, 0.52011868],
       [0.00804528, 0.20485437, 0.66992803],
       [0.2525078 , 0.33219828, 0.39886931],
       [0.83348114, 0.65134476, 0.61855269]])

In [28]:
random_array_2.shape

(5, 3)

In [29]:
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.59703561, 0.52838893, 0.56642112],
       [0.72502603, 0.61591048, 0.76825928],
       [0.70256104, 0.68428672, 0.22606377],
       [0.45082985, 0.45089376, 0.28246921],
       [0.23627818, 0.13810489, 0.98858954]])

In [30]:
# Pseudo-random numbers
np.random.seed(seed=99999)
random_array_4 = np.random.randint(10, size=(5, 3))
random_array_4

array([[0, 3, 1],
       [8, 1, 3],
       [8, 5, 6],
       [0, 6, 0],
       [4, 0, 9]])

In [31]:
np.random.seed(7)
random_array_5 = np.random.random((5, 3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

## 3. Viewing arrays and matrices

In [32]:
np.unique(random_array_4)

array([0, 1, 3, 4, 5, 6, 8, 9])

In [33]:
random_array_4

array([[0, 3, 1],
       [8, 1, 3],
       [8, 5, 6],
       [0, 6, 0],
       [4, 0, 9]])

In [34]:
a1

array([1, 2, 3])

In [35]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [36]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [37]:
a1[0]

1

In [38]:
a2[0]

array([1. , 2. , 3.3])

In [39]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [41]:
a4 = np.random.randint(10, size=(2, 3, 4, 5))

a4

array([[[[3, 5, 8, 8, 7],
         [5, 0, 0, 2, 8],
         [9, 6, 4, 9, 7],
         [3, 3, 8, 3, 0]],

        [[1, 0, 0, 6, 7],
         [7, 9, 3, 0, 7],
         [7, 7, 0, 5, 4],
         [3, 1, 3, 1, 3]],

        [[4, 3, 1, 9, 5],
         [9, 1, 2, 3, 2],
         [2, 5, 7, 3, 0],
         [9, 9, 3, 4, 5]]],


       [[[3, 0, 4, 8, 6],
         [7, 2, 7, 3, 8],
         [6, 6, 5, 6, 5],
         [7, 1, 5, 4, 4]],

        [[9, 9, 0, 6, 2],
         [6, 8, 2, 4, 1],
         [6, 1, 5, 1, 6],
         [9, 8, 6, 5, 9]],

        [[7, 5, 4, 9, 6],
         [8, 1, 5, 5, 8],
         [3, 7, 7, 9, 4],
         [7, 5, 9, 6, 2]]]])

In [42]:
# Get the first 4 numbers of the inner most arrays

a4[:, :, :, :4]

array([[[[3, 5, 8, 8],
         [5, 0, 0, 2],
         [9, 6, 4, 9],
         [3, 3, 8, 3]],

        [[1, 0, 0, 6],
         [7, 9, 3, 0],
         [7, 7, 0, 5],
         [3, 1, 3, 1]],

        [[4, 3, 1, 9],
         [9, 1, 2, 3],
         [2, 5, 7, 3],
         [9, 9, 3, 4]]],


       [[[3, 0, 4, 8],
         [7, 2, 7, 3],
         [6, 6, 5, 6],
         [7, 1, 5, 4]],

        [[9, 9, 0, 6],
         [6, 8, 2, 4],
         [6, 1, 5, 1],
         [9, 8, 6, 5]],

        [[7, 5, 4, 9],
         [8, 1, 5, 5],
         [3, 7, 7, 9],
         [7, 5, 9, 6]]]])

## 4. Manipulating & comparing arrays

### Arthmetic

In [44]:
a1

array([1, 2, 3])

In [45]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [46]:
a1 + ones

array([[2., 3., 4.],
       [2., 3., 4.]])

In [47]:
a1 - ones

array([[0., 1., 2.],
       [0., 1., 2.]])

In [48]:
a1 * ones


array([[1., 2., 3.],
       [1., 2., 3.]])

In [49]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [50]:
a1 * a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [51]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [52]:
a2 * a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [53]:
a1 / ones

array([[1., 2., 3.],
       [1., 2., 3.]])

In [54]:
a2 / a1

array([[1.        , 1.        , 1.1       ],
       [4.        , 2.5       , 2.16666667]])

In [55]:
# Floor division removes the decimals (rounds down)
a2 // a1

array([[1., 1., 1.],
       [4., 2., 2.]])

In [56]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [57]:
a2 ** 2

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [58]:
np.square(a2)

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [59]:
np.add(a1, ones)

array([[2., 3., 4.],
       [2., 3., 4.]])

In [60]:
a1 % 2

array([1, 0, 1], dtype=int32)

In [61]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [62]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

### Aggregation

Aggregation = performing the same operation on a number of things

In [64]:
listy_list = [1, 2, 3]
type(listy_list)

list

In [65]:
sum(listy_list)

6

In [66]:
a1

array([1, 2, 3])

In [67]:
type(a1)

numpy.ndarray

In [68]:
sum(a1)

6

In [69]:
np.sum(a1)

6

Use Python's methods (`sum()`) on Python datatypes and use NumPy's methods on NumPy arrays (`np.sum()`).

In [70]:
# Create a massive NumPy Array
massive_array = np.random.random(100000)
massive_array.size

100000

In [72]:
massive_array[:10]

array([0.82845319, 0.94180927, 0.12814785, 0.23043067, 0.6591584 ,
       0.13247399, 0.22407864, 0.57486259, 0.16952372, 0.78223015])

In [73]:
%timeit sum(massive_array) # Python's sum()
%timeit np.sum(massive_array) # NumPy's sum()

5.46 ms ± 79.1 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)
25.6 μs ± 574 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [74]:
5460 / 25.6

213.28125

In [75]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [76]:
np.mean(a2)

3.6333333333333333

In [77]:
np.max(a2)

6.5

In [78]:
np.min(a2)

1.0

In [79]:
# Standard deviation = a mesure of how spread out a group of numbers is from the mean
np.std(a2)

1.8226964152656422

In [80]:
# Variance = mesure of the average degree to which each number is different to the mean
# Higher variance = wider range of numbers
# Lower variance = lower range of numbers
np.var(a2)

3.3222222222222224

In [81]:
# Standard deviation = squareroot of variance
np.sqrt(np.var(a2))

1.8226964152656422