In [1]:
import numpy as np

## DataTypes and Attributes

In [2]:
# NumPy's main datatype is ndarray

In [3]:
a1 = np.array([1, 2, 3])

In [4]:
a1

array([1, 2, 3])

In [9]:
a2 = np.array([[1, 2, 3], [4, 5, 6.5]])

In [6]:
a1.shape

(3,)

In [10]:
a2.shape

(2, 3)

In [11]:
a1.ndim

1

In [12]:
a2.ndim

2

In [13]:
a1.dtype

dtype('int64')

In [14]:
a2.dtype

dtype('float64')

In [15]:
a1.size

3

In [16]:
a2.size

6

In [17]:
type(a1)

numpy.ndarray

In [18]:
# Create a DataFrame from NumPy array
import pandas as pd
df = pd.DataFrame(a2)

In [19]:
df

,0,1,2
0,1.0,2.0,3.0
1,4.0,5.0,6.5


## Creating arrays

In [21]:
ones = np.ones((2, 3))

In [22]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [23]:
ones.dtype

dtype('float64')

In [24]:
type(ones)

numpy.ndarray

In [25]:
zeros = np.zeros((2, 3))

In [26]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [27]:
range_array = np.arange(0, 10, 2)

In [28]:
range_array

array([0, 2, 4, 6, 8])

In [29]:
random_array = np.random.randint(0, 10, size=(3, 5))

In [30]:
random_array

array([[8, 7, 3, 1, 6],
       [1, 7, 2, 6, 8],
       [8, 7, 0, 4, 0]], dtype=int32)

In [31]:
random_array.size

15

In [32]:
len(random_array)

3

In [33]:
random_array.shape

(3, 5)

In [34]:
random_array_2 = np.random.random((5, 3))

In [35]:
random_array_2

array([[0.73578618, 0.13654223, 0.74131173],
       [0.24156889, 0.70967862, 0.19892681],
       [0.4765054 , 0.0758437 , 0.76005524],
       [0.5929158 , 0.65737191, 0.13009607],
       [0.75721644, 0.67162725, 0.52942205]])

In [36]:
random_array_3 = np.random.rand(5, 3)

In [37]:
random_array_3

array([[0.75987115, 0.67912166, 0.49617909],
       [0.32972486, 0.82252374, 0.40203427],
       [0.41301779, 0.4821006 , 0.75108204],
       [0.84066001, 0.5195795 , 0.64629214],
       [0.87190469, 0.12224348, 0.3453536 ]])

In [38]:
# Pseudo-random numbers
np.random.seed()