In [3]:
import numpy as np

## DataTypes & Attributes

In [4]:
# NumPy's main datatype is ndarray
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [5]:
type(a1)

numpy.ndarray

In [6]:
a2 = np.array([[1, 2.0, 3.3], [4, 5, 6.5]])

a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [7]:
a3 = np.array([[[1, 2, 3],
               [4, 5, 6],
              [7, 8, 9]],
             [[10, 11, 12],
             [13, 14, 15],
             [16, 17, 18]]])

In [8]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [9]:
a1.shape

(3,)

In [10]:
a2.shape

(2, 3)

In [11]:
a3.shape

(2, 3, 3)

In [12]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [13]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [14]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [15]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [16]:
# Create a DataFrame from a NumPy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## 2. Creating arrays

In [17]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [18]:
sample_array.dtype

dtype('int32')

In [20]:
ones = np.ones((2, 3))

In [21]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [22]:
ones.dtype

dtype('float64')

In [24]:
type(ones)

numpy.ndarray

In [25]:
zeros = np.zeros((2, 3))

In [26]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [27]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [28]:
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[5, 4, 0, 6, 4],
       [0, 4, 0, 4, 5],
       [2, 4, 6, 8, 1]])

In [29]:
random_array.size

15

In [31]:
random_array.shape

(3, 5)

In [32]:
random_array_2 = np.random.random((5, 3))

random_array_2

array([[0.07116334, 0.42658616, 0.40095249],
       [0.43138279, 0.94450788, 0.98544721],
       [0.15723371, 0.21260321, 0.53795834],
       [0.92021687, 0.00436643, 0.3370036 ],
       [0.62981229, 0.64005768, 0.34266983]])

In [33]:
random_array_2.shape

(5, 3)

In [34]:
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.2829802 , 0.86328757, 0.85822989],
       [0.12800304, 0.53284097, 0.373837  ],
       [0.73085422, 0.10164705, 0.26301154],
       [0.23820295, 0.55922386, 0.98167202],
       [0.44602493, 0.77504984, 0.85114663]])

In [36]:
# Pseudo-random numbers
n = np.random.seed()
n