In [1]:
import numpy as np

## DataTypes & Attributes

In [2]:
# NumPy's main datatype is ndarray
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1, 2.0, 3.3], [4, 5, 6.5]])

a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [5]:
a3 = np.array([[[1, 2, 3],
               [4, 5, 6],
              [7, 8, 9]],
             [[10, 11, 12],
             [13, 14, 15],
             [16, 17, 18]]])

In [6]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [7]:
a1.shape

(3,)

In [8]:
a2.shape

(2, 3)

In [9]:
a3.shape

(2, 3, 3)

In [10]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [11]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [12]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [13]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [14]:
# Create a DataFrame from a NumPy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## 2. Creating arrays

In [15]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [16]:
sample_array.dtype

dtype('int32')

In [17]:
ones = np.ones((2, 3))

In [18]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [19]:
ones.dtype

dtype('float64')

In [20]:
type(ones)

numpy.ndarray

In [21]:
zeros = np.zeros((2, 3))

In [22]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [24]:
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[7, 7, 3, 4, 9],
       [8, 9, 8, 2, 3],
       [5, 8, 6, 3, 6]])

In [25]:
random_array.size

15

In [26]:
random_array.shape

(3, 5)

In [27]:
random_array_2 = np.random.random((5, 3))

random_array_2

array([[0.10543662, 0.49900599, 0.69264641],
       [0.40539691, 0.23963603, 0.33053905],
       [0.06472005, 0.07555705, 0.97763543],
       [0.60957728, 0.20973323, 0.41649223],
       [0.71437809, 0.25881321, 0.87588896]])

In [28]:
random_array_2.shape

(5, 3)

In [29]:
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.63718326, 0.46427092, 0.20672175],
       [0.84549446, 0.42191109, 0.3838668 ],
       [0.65003432, 0.19606601, 0.049988  ],
       [0.39541807, 0.43706195, 0.73822054],
       [0.42774434, 0.74822637, 0.33968991]])

In [30]:
# Pseudo-random numbers
np.random.seed(seed=99999)
random_array_4 = np.random.randint(10, size=(5, 3))
random_array_4

array([[0, 3, 1],
       [8, 1, 3],
       [8, 5, 6],
       [0, 6, 0],
       [4, 0, 9]])

In [31]:
np.random.seed(7)
random_array_5 = np.random.random((5, 3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

## 3. Viewing arrays and matrices

In [32]:
np.unique(random_array_4)

array([0, 1, 3, 4, 5, 6, 8, 9])

In [33]:
random_array_4

array([[0, 3, 1],
       [8, 1, 3],
       [8, 5, 6],
       [0, 6, 0],
       [4, 0, 9]])

In [34]:
a1

array([1, 2, 3])

In [35]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [36]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [37]:
a1[0]

1

In [38]:
a2[0]

array([1. , 2. , 3.3])

In [39]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [41]:
a4 = np.random.randint(10, size=(2, 3, 4, 5))

a4

array([[[[3, 5, 8, 8, 7],
         [5, 0, 0, 2, 8],
         [9, 6, 4, 9, 7],
         [3, 3, 8, 3, 0]],

        [[1, 0, 0, 6, 7],
         [7, 9, 3, 0, 7],
         [7, 7, 0, 5, 4],
         [3, 1, 3, 1, 3]],

        [[4, 3, 1, 9, 5],
         [9, 1, 2, 3, 2],
         [2, 5, 7, 3, 0],
         [9, 9, 3, 4, 5]]],


       [[[3, 0, 4, 8, 6],
         [7, 2, 7, 3, 8],
         [6, 6, 5, 6, 5],
         [7, 1, 5, 4, 4]],

        [[9, 9, 0, 6, 2],
         [6, 8, 2, 4, 1],
         [6, 1, 5, 1, 6],
         [9, 8, 6, 5, 9]],

        [[7, 5, 4, 9, 6],
         [8, 1, 5, 5, 8],
         [3, 7, 7, 9, 4],
         [7, 5, 9, 6, 2]]]])

In [42]:
# Get the first 4 numbers of the inner most arrays

a4[:, :, :, :4]

array([[[[3, 5, 8, 8],
         [5, 0, 0, 2],
         [9, 6, 4, 9],
         [3, 3, 8, 3]],

        [[1, 0, 0, 6],
         [7, 9, 3, 0],
         [7, 7, 0, 5],
         [3, 1, 3, 1]],

        [[4, 3, 1, 9],
         [9, 1, 2, 3],
         [2, 5, 7, 3],
         [9, 9, 3, 4]]],


       [[[3, 0, 4, 8],
         [7, 2, 7, 3],
         [6, 6, 5, 6],
         [7, 1, 5, 4]],

        [[9, 9, 0, 6],
         [6, 8, 2, 4],
         [6, 1, 5, 1],
         [9, 8, 6, 5]],

        [[7, 5, 4, 9],
         [8, 1, 5, 5],
         [3, 7, 7, 9],
         [7, 5, 9, 6]]]])

## 4. Manipulating & comparing arrays

### Arthmetic

In [43]:
a1

array([1, 2, 3])

In [44]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [45]:
a1 + ones

array([[2., 3., 4.],
       [2., 3., 4.]])

In [46]:
a1 - ones

array([[0., 1., 2.],
       [0., 1., 2.]])

In [47]:
a1 * ones


array([[1., 2., 3.],
       [1., 2., 3.]])

In [48]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [49]:
a1 * a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [50]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [51]:
a2 * a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [ ]:
a1 / ones

In [ ]:
a2 / a1

In [ ]:
# Floor division removes the decimals (rounds down)
a2 // a1

In [ ]:
a2

In [ ]:
a2 ** 2

In [ ]:
np.square(a2)

In [ ]:
np.add(a1, ones)

In [ ]:
a1 % 2

In [ ]:
np.exp(a1)

In [ ]:
np.log(a1)

### Aggregation

Aggregation = performing the same operation on a number of things

In [ ]:
listy_list = [1, 2, 3]
type(listy_list)

In [ ]:
sum(listy_list)

In [ ]:
a1

In [ ]:
type(a1)

In [ ]:
sum(a1)

In [ ]:
np.sum(a1)

Use Python's methods (`sum()`) on Python datatypes and use NumPy's methods on NumPy arrays (`np.sum()`).

In [ ]:
# Create a massive NumPy Array
massive_array = np.random.random(100000)
massive_array.size

In [ ]:
massive_array[:10]

In [ ]:
%timeit sum(massive_array) # Python's sum()
%timeit np.sum(massive_array) # NumPy's sum()

In [ ]:
5460 / 25.6

In [ ]:
a2

In [ ]:
np.mean(a2)

In [ ]:
np.max(a2)

In [ ]:
np.min(a2)

In [ ]:
# Standard deviation = a mesure of how spread out a group of numbers is from the mean
np.std(a2)

In [ ]:
# Variance = mesure of the average degree to which each number is different to the mean
# Higher variance = wider range of numbers
# Lower variance = lower range of numbers
np.var(a2)

In [ ]:
# Standard deviation = squareroot of variance
np.sqrt(np.var(a2))

In [ ]:
# Demo of std and var
high_var_array = np.array([1, 100, 200, 300, 4000, 5000])
low_var_array = np.array([2, 4, 6, 8, 10])

In [ ]:
np.var(high_var_array), np.var(low_var_array)

In [ ]:
np.std(high_var_array), np.std(low_var_array)

In [ ]:
np.mean(high_var_array), np.mean(low_var_array)

In [ ]:
%matplotlib inline
import matplotlib.pyplot as plt

plt.hist(high_var_array)
plt.show()

In [ ]:
plt.hist(low_var_array)
plt.show()

## Reshaping & transposing

In [ ]:
a2

In [ ]:
a2.shape

In [ ]:
a3

In [ ]:
a3.shape

In [ ]:
a2 * a3

In [ ]:
a2.shape

In [ ]:
a2.reshape(2, 3, 1)

In [ ]:
a2

In [ ]:
a2.shape

In [ ]:
a2_reshape = a2.reshape(2, 3, 1)

In [ ]:
a2_reshape

In [ ]:
a2_reshape * a3

In [ ]:
# Transpose = Switches the axis
a2.T

In [ ]:
a2

## Dot product

In [ ]:
np.random.seed(0)

mat1 = np.random.randint(10, size=(5, 3))
mat2 = np.random.randint(10, size=(5, 3))

mat1

In [ ]:
mat2

In [ ]:
mat1.shape, mat2.shape

In [ ]:
# Element-wise multiplication (Hadamard product)
mat1 * mat2

In [ ]:
# Dot product
np.dot(mat1, mat2)

In [ ]:
mat3 = np.dot(mat1, mat2.T)
mat3

In [ ]:
mat3.shape

## Dot product example (nut butter sales)

In [ ]:
np.random.seed(0)

# Number of jars sold
sales_amounts = np.random.randint(20, size=(5, 3))
sales_amounts

In [ ]:
# Creeate weekly_sales DataFrame
weekly_sales = pd.DataFrame(sales_amounts,
                            index=["Mon", "Tues", "Wed", "Thurs", "Fri"],
                           columns=["Almond butter", "Peanut butter", "Cashew butter"])

weekly_sales

In [ ]:
# Create prices array
prices = np.array([10, 8, 12])
prices

In [ ]:
# Create butter_prices DataFrame
butter_prices = pd.DataFrame(prices.reshape(1, 3),
                             index=["Price"],
                             columns=["Almond butter", "Peanut butter", "Cashew butter"]
                            )

butter_prices

In [ ]:
# Shape aren't aligned, let's transpose
total_sales = prices.dot(sales_amounts.T)
total_sales

In [ ]:
daily_sales = butter_prices.dot(weekly_sales.T)
daily_sales

In [ ]:
# Doesn't work =, not the right shape
weekly_sales["Total ($)"] = daily_sales
weekly_sales

In [ ]:
weekly_sales["Total ($)"] = daily_sales.T
weekly_sales

### Comparison Operators

In [ ]:
a1, a2

In [ ]:
a1 > a2

In [ ]:
a1 >= a2

In [ ]:
a1 > 5

In [ ]:
a1 < 5

In [ ]:
a1 == a1

In [ ]:
random_array

In [ ]:
np.sort(random_array)

In [ ]:
np.argsort(random_array)

In [ ]:
a1

In [ ]:
np.argsort(a1)

In [52]:
random_array

array([[7, 7, 3, 4, 9],
       [8, 9, 8, 2, 3],
       [5, 8, 6, 3, 6]])

In [53]:
np.argmax(random_array)

4

## 6. Practical Example - NumPy in Action!

<img src="images/panda.png" />

In [55]:
# Turn an image into a NumPy array

from matplotlib.image import imread

panda = imread("images/panda.png")

print(type(panda))

<class 'numpy.ndarray'>


In [56]:
panda

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       ...,

       [[0.13333334, 0.07450981, 0.05490196],
        [0.12156863, 0.0627451 , 0.04313726],
        [0.10980392, 0

In [57]:
panda.size, panda.shape, panda.ndim

(24465000, (2330, 3500, 3), 3)

In [58]:
panda[:5]

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.

<img src="images/car-photo.png" />

In [59]:
car = imread("images/car-photo.png")
print(type(car))

<class 'numpy.ndarray'>


In [60]:
car

array([[[0.5019608 , 0.50980395, 0.4862745 , 1.        ],
        [0.3372549 , 0.34509805, 0.30588236, 1.        ],
        [0.20392157, 0.21568628, 0.14901961, 1.        ],
        ...,
        [0.64705884, 0.7058824 , 0.54901963, 1.        ],
        [0.59607846, 0.63529414, 0.45882353, 1.        ],
        [0.44705883, 0.47058824, 0.3372549 , 1.        ]],

       [[0.44313726, 0.43529412, 0.40392157, 1.        ],
        [0.3137255 , 0.31764707, 0.27450982, 1.        ],
        [0.2       , 0.21176471, 0.14117648, 1.        ],
        ...,
        [0.5058824 , 0.5372549 , 0.4117647 , 1.        ],
        [0.49803922, 0.52156866, 0.39607844, 1.        ],
        [0.4       , 0.42745098, 0.34117648, 1.        ]],

       [[0.39607844, 0.38039216, 0.34117648, 1.        ],
        [0.31764707, 0.3137255 , 0.27450982, 1.        ],
        [0.28627452, 0.29411766, 0.24705882, 1.        ],
        ...,
        [0.44705883, 0.45882353, 0.32156864, 1.        ],
        [0.45882353, 0.482352

In [61]:
car[:1]

array([[[0.5019608 , 0.50980395, 0.4862745 , 1.        ],
        [0.3372549 , 0.34509805, 0.30588236, 1.        ],
        [0.20392157, 0.21568628, 0.14901961, 1.        ],
        ...,
        [0.64705884, 0.7058824 , 0.54901963, 1.        ],
        [0.59607846, 0.63529414, 0.45882353, 1.        ],
        [0.44705883, 0.47058824, 0.3372549 , 1.        ]]], dtype=float32)

<img src="images/dog-photo.png" />

In [63]:
dog = imread("images/dog-photo.png")

print(type(dog))

<class 'numpy.ndarray'>
